services:
  postgres:
    image: postgres:15-alpine
    container_name: notification-service-db
    environment:
      POSTGRES_DB: notification_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  mailhog:
    image: mailhog/mailhog
    container_name: notification-service-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI (http://localhost:8025)

  backend:
    build: ./backend
    container_name: notification-service-backend
    environment:
      DB_HOST: 195.38.164.168
      DB_PORT: 5432
      DB_NAME: notification_service
      DB_USERNAME: notification_user
      DB_PASSWORD: NotificationPass123!

      # Реальный SMTP
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: openweserver@gmail.com
      SPRING_MAIL_PASSWORD: cekgbswtttgzklja
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:

