services:
  postgres:
    image: postgres:15-alpine
    container_name: notification-service-db
    environment:
      POSTGRES_DB: notification_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./backend
    container_name: notification-service-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: notification_service
      # В будущем при переходе БД на сервер укажем значения для отдельного пользователя
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

      # Реальный SMTP
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: openweserver@gmail.com
      SPRING_MAIL_PASSWORD: cekgbswtttgzklja
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:

