spring:
  application:
    name: whatsapp-worker

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
    listener:
      simple:
        missing-queues-fatal: false
        acknowledge-mode: auto

server:
  port: ${SERVER_PORT:8081}

app:
  rabbit:
    exchangeNotification: ${EXCHANGE_NOTIFICATION:x.notification}
    exchangeStatus: ${EXCHANGE_STATUS:x.notification.status}

    routingWhatsapp: ${ROUTING_WHATSAPP:whatsapp}
    queueWhatsapp: ${QUEUE_WHATSAPP:q.notification.whatsapp}
    queueStatusGateway: ${QUEUE_STATUS_GATEWAY:q.notification.status.gateway}

    whatsappRetryQueues:
      - ${WHATSAPP_RETRY_Q1:ns.whatsapp.retry.5s}
      - ${WHATSAPP_RETRY_Q2:ns.whatsapp.retry.30s}
      - ${WHATSAPP_RETRY_Q3:ns.whatsapp.retry.60s}
    whatsappDlq: ${WHATSAPP_DLQ:ns.whatsapp.dlq}


  api:
    # Twilio WhatsApp API URL
    base-url: https://api.twilio.com/2010-04-01/Accounts/AC4a0e9d8445e0e4ab389e984268d2af83/Messages.json

    # ВАШ ПРАВИЛЬНЫЙ ТОКЕН (тот что вы сгенерировали):
    token: Basic QUM0YTBlOWQ4NDQ1ZTBlNGFiMzg5ZTk4NDI2OGQyYWY4Mzo5OTFkMjQ1YWYzYjc0NGU1MzRjYWU5YzJlYWU0ZDNhYg==
    from-number: "whatsapp:+14155238886"  # ← ДОБАВЬТЕ ЭТО
    timeout-ms: 30000
    max-retries: 3



logging:
  level:
    root: INFO
    kg.notifications.whatsapp: DEBUG
    org.springframework.amqp: INFO
    org.springframework.web.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: logs/whatsapp-worker.log